import type { Metadata } from "next"
import { Inter } from "next/font/google"

import Footer from "@/components/layout/footer"
import Header from "@/components/layout/header"
import Notification from "@/components/layout/header/notification"

import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Notification />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
